// <auto-generated />
namespace wt4u.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Start_End_Break : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Start_End_Break));
        
        string IMigrationMetadata.Id
        {
            get { return "201404270808227_Start_End_Break"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
